id: :id
type: :type
time: :date
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: :author
        title: :title
        keywords:
        description:
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
