id: emmet2html
type: plugin
time: 2015-11-11 17:56
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: emmet语法生成html
        keywords: emmet,转html,插件
        description: >
            有感于 emmet 语法的方便，编写了一个js插件，把 emmet字符串 转为 html代码。
            纯手打，不依赖外部脚本。
