id: 1457338910434
type: note
time: 2015-10-15 16:21
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: FormData、XMLHttpRequest带进度的上传
        keywords: 文件上传,进度
        description: 前端文件上传的基本原理
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
