id: 1457335784717
type: note
time: 2015-11-01 10:01
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: glob通配符
        keywords: glob
        description: 在 node.js 中，经常用到的一个匹配库，minimatch，其中使用的，就是glob通配符
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
