id: 1457342664218
type: note
time: 2015-08-11 17:24
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: perspective记录
        keywords:  css3,3d
        description: 记录下 css3 perspective相关的属性
        withoutHomeDescription: true
        # 首页描述 homeDescription:
