id: yml-simple-introduce
type: blog
time: 2015-10-25 19:44
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: YAML简单介绍
        keywords: yaml,yml学习,yml前端应用
        description: >
            简介YAML[ Yet Another Markup Language ]英译过来，就是“另一门标志语言”。它是一种直观的，容易被人类阅读，以及被机器识别的数据格式。
            它类似于XML和，但语法上，要比前者简洁很多。
