id: 1457330875394
type: note
time: 2015-09-07 14:07
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: 常用的meta
        keywords: meta
        description: 记录常用的meta设置
        withoutHomeDescription: true
        # 首页描述 homeDescription:
