id: fliter-grayscale
type: blog
time: 2015-11-18 18:40
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: Css3 grayscale 滤镜
        keywords: grayscale滤镜,兼容
        description: >
            兼容全浏览器的图片变灰操作，通过css3 filter、ie 滤镜、svg背景等方法，达到全浏览图片变灰操作。
            使用脚本，对不支持IE滤镜，也不支持css3滤镜的情况，进行处理。
