id: full-screen-switch
type: blog
time: 2016-10-27 10:09
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端
    - 移动

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: 全屏切换笔记
        keywords: 移动,全屏切换
        description: 移动端经常有全屏切换的需求，推荐一个小巧的插件 slip.js
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
