id: project-js
type: plugin
time: 2015-11-1 11:30
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: 编写简单的模块加载器
        keywords: javascript模块加载,require,define
        description: 分析一个模板加载器，需要的主要方法，以及相关注意事项，本文并不会做详细的编写。
