id: process-stdout
type: note
time: 2016-01-14 15:04
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: process.stdout随手记录[node.js]
        keywords: process输出流
        description: node.js输出流随手录
        withoutHomeDescription: true
