id: 1457338275156
type: note
time: 2015-10-15 17:11
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: 监听文件[夹]更变
        keywords: node.js,监听文件更变
        description: 分析node.js中，监听文件夹更变的一些方法
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
