id: higthcharts
type: blog
time: 2016-01-14 9:44
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端,图表

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: highcharts使用学习
        keywords: jquery插件,highcharts,绘制图表
        description: >
                    Highcharts是一个非常流行，界面美观的javascript图标库。<br/>
                    目前支持直线图、曲线图、面积图、柱状图、饼图、散点图等多达18种不同类型的图表[4.2.1版本]。<br/>
                    Highcharts支持目前的所有现代浏览器，包括IE6+、iPhone/iPad、Android等。<br/>
                    它在标准浏览器中，使用SVG技术渲染图片，在遗留的IE浏览器中，使用VML技术来绘图。
