id: san-not-full-learn
type: note
time: 2018-09-14 11:10
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
poster: ./asset/poster.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: san.js的一次不完全实践
        keywords:
        description: >
            san.js，是一款体积小巧，兼容性好（IE6），性能卓越，是一个可靠、可依赖的实现响应式用户界面的解决方案
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
