id: 1459390671643
type: note
time: 2016-03-31 10:17
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: mongodb学习-01
        keywords: mongodb,增删查该
        description: mongodb简单学习 01
        withoutHomeDescription: true
        # 首页描述 homeDescription:
