id: 1481251257718
type: blog
time: 2016-12-09 10:40
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: 元素自动进入屏幕可是区域
        keywords: js,可是区域,scrollIntoView
        description: 介绍dom的scrollIntoView方法
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
