id: 1457336270002
type: note
time: 2015-10-16 16:02
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: webpage-phantomjs的重要板块
        keywords: phantomjs
        description: 介绍 phantomjs 中的webpage板块
        # 是否不显示首页描述 withoutHomeDescription: true
        # 首页描述 homeDescription:
