id: javascript-regexp-learn
type: blog
time: 2015-10-25 19:35
# 首页
main: index.md
# 默认模板
template: article.html

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: '[入门]javascript正则表达式'
        keywords: javascript,正则,入门
        description: >
            正则表达式，又称正规表示法。它使用单个字符串来描述、匹配一系列符合某个规律的字符串。在很多文本编辑器中，正则表达式用于检索、替换某些符合某种规则的文本。<br/>
            本文主要讲述 javascript 中，所有设计正则的方法，以及正则的一些语法，和注意事项。
