id: 1457335374768
type: note
time: 2015-10-27 16:22
# 首页
main: index.md
# 默认模板
template: article.html
# 海报地址
# poster: ./assert/help.png

tags:
    - 前端

# 每个页面特有的参数
options:
    index.md:
        author: da宗熊
        title: node.js中的目录
        keywords: __dirname等
        description: 在 node.js 中，有几个路径，是一定需要弄清楚的
        withoutHomeDescription: true
        # 首页描述 homeDescription:
